// my-app/src/components/List.tsx
import type { Task } from "./ShowTasks"
import { WS_BASE_URL } from "../settings"
import ChannelHook from "../hooks/ChannelHook"
import { toast } from "react-toastify"
import { useState } from "react"
import { TitleOrTextInput } from "./utils"
import { change_list_title, change_task_list, change_task_title, create_task, delete_task, remove_list } from "../generated"

export type List = {
  id: number
  title: string
  tasks: Task[]
}

let currentlyDragging: { id: number; list_id: number } | null = null

/* ── Single task card ── */

function TaskCard({ task, listId }: { task: Task; listId: number }) {
  return (
    <div
      className="task-card"
      draggable
      onDragStart={() => { currentlyDragging = { id: task.id, list_id: listId } }}
      onDragEnd={() => { currentlyDragging = null }}
    >
      <div className="task-card__handle">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
          <circle cx="8" cy="4" r="2" /><circle cx="16" cy="4" r="2" />
          <circle cx="8" cy="12" r="2" /><circle cx="16" cy="12" r="2" />
          <circle cx="8" cy="20" r="2" /><circle cx="16" cy="20" r="2" />
        </svg>
      </div>

      <div className="task-card__body">
        <TitleOrTextInput
          text={task.title}
          onChange={(newName) => {
            if (!newName) {
              toast.error('Task name is required')
              return
            }
            change_task_title(task.id, newName)
          }}
        />
        {task.description && <p>{task.description}</p>}
      </div>

      <button
        className="btn-danger btn-icon task-card__delete"
        onClick={() => delete_task(listId, task.id)}
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M18 6 6 18M6 6l12 12" />
        </svg>
      </button>
    </div>
  )
}

/* ── Full list column ── */

export function TaskList({ list, board_id }: { list: List; board_id: number }) {
  const wsUrl = `${WS_BASE_URL}/list/${list.id}`
  const [isDragOver, setIsDragOver] = useState(false)
  const [showAddTask, setShowAddTask] = useState(false)
  const tasks = ChannelHook<Task>(wsUrl)
  const taskCount = Object.keys(tasks).length

  return (
    <div
      className={`column${isDragOver ? ' column--drag-over' : ''}`}
      onDragOver={(e) => {
        e.preventDefault()
        setIsDragOver(true)
      }}
      onDragLeave={() => setIsDragOver(false)}
      onDrop={(e) => {
        e.preventDefault()
        setIsDragOver(false)
        if (!currentlyDragging) {
          toast.error('No task is being dragged')
          return
        }
        change_task_list(currentlyDragging.id, currentlyDragging.list_id, list.id)
        currentlyDragging = null
      }}
    >
      {/* Header */}
      <div className="column__header">
        <div className="column__header-left">
          <TitleOrTextInput
            text={list.title}
            onChange={(newTitle) => change_list_title(list.id, newTitle)}
          />
          <span className="column__count">{taskCount}</span>
        </div>
        <div className="column__actions">
          <button
            className="btn-danger btn-icon"
            onClick={() => remove_list(board_id, list.id)}
            title="Delete list"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
            </svg>
          </button>
        </div>
      </div>

      {/* Tasks */}
      <div className="column__body">
        {Object.values(tasks).map((task) => (
          <TaskCard key={task.id} task={task} listId={list.id} />
        ))}
      </div>

      {/* Footer — Add task */}
      <div className="column__footer">
        {!showAddTask ? (
          <button className="add-task-trigger" onClick={() => setShowAddTask(true)}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 5v14M5 12h14" />
            </svg>
            Add a task
          </button>
        ) : (
          <form
            className="add-task-form"
            onSubmit={(e) => {
              e.preventDefault()
              const formData = new FormData(e.target as HTMLFormElement)
              const name = formData.get('name') as string
              if (!name) return
              create_task(list.id, name);
              (e.target as HTMLFormElement).reset()
            }}
          >
            <input type="text" name="name" placeholder="What needs to be done?" autoFocus />
            <div className="add-task-form__actions">
              <button type="submit" className="btn-primary">Add</button>
              <button type="button" className="btn-ghost" onClick={() => setShowAddTask(false)}>Cancel</button>
            </div>
          </form>
        )}
      </div>
    </div>
  )
}

// my-vue-app/src/components/List.vue
<script setup lang="ts">
import { onUnmounted, ref } from 'vue'
import UseChannelHook from '../ChannelHook'
import InlineEdit from './InlineEdit.vue'
import { WS_BASE_URL } from '../settings'
import {
  create_task,
  delete_task,
  remove_list,
  change_list_title,
  change_task_title,
  change_task_list,
} from '../generated'

type Task = {
    id: number;
    title: string;
    description: string;
}

const props = defineProps<{
    list_id: number;
    title?: string;
    board_id: number;
}>()

const [tasks, ws] = UseChannelHook<Task>(`${WS_BASE_URL}/list/${props.list_id}`)

onUnmounted(() => {
    ws.close();
})

const showAddTask = ref(false)
const isDragOver = ref(false)

function handleCreateTask(e: Event) {
  e.preventDefault()
  const form = e.target as HTMLFormElement
  const formData = new FormData(form)
  const name = formData.get('name') as string
  if (!name) return
  create_task(props.list_id, name)
  form.reset()
}

// --- Drag and drop ---

// Module-level drag state shared across all List instances
declare global {
  interface Window {
    __kanban_dragging?: { id: number; list_id: number } | null;
  }
}

function onTaskDragStart(taskId: number) {
  window.__kanban_dragging = { id: taskId, list_id: props.list_id }
}

function onTaskDragEnd() {
  window.__kanban_dragging = null
}

function onColumnDragOver(e: DragEvent) {
  e.preventDefault()
  isDragOver.value = true
}

function onColumnDragLeave() {
  isDragOver.value = false
}

function onColumnDrop(e: DragEvent) {
  e.preventDefault()
  isDragOver.value = false
  const dragging = window.__kanban_dragging
  if (!dragging) return
  if (dragging.list_id !== props.list_id) {
    change_task_list(dragging.id, dragging.list_id, props.list_id)
  }
  window.__kanban_dragging = null
}
</script>

<template>
  <div
    class="column"
    :class="{ 'column--drag-over': isDragOver }"
    @dragover="onColumnDragOver"
    @dragleave="onColumnDragLeave"
    @drop="onColumnDrop"
  >
    <!-- Header -->
    <div class="column__header">
      <div class="column__header-left">
        <InlineEdit
          :text="title ?? `List ${list_id}`"
          @change="(val: string) => change_list_title(list_id, val)"
        />
        <span class="column__count">{{ Object.keys(tasks).length }}</span>
      </div>
      <div class="column__actions">
        <button
          class="btn-danger btn-icon"
          @click="remove_list(board_id, list_id)"
          title="Delete list"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/>
            <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
          </svg>
        </button>
      </div>
    </div>

    <!-- Body — task cards -->
    <div class="column__body">
      <div
        v-for="(task, index) in Object.values(tasks)"
        :key="task.id"
        class="task-card"
        draggable="true"
        :style="{ animationDelay: `${index * 60}ms` }"
        @dragstart="onTaskDragStart(task.id)"
        @dragend="onTaskDragEnd"
      >
        <span class="task-card__handle">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor">
            <circle cx="9" cy="6" r="2"/><circle cx="15" cy="6" r="2"/>
            <circle cx="9" cy="12" r="2"/><circle cx="15" cy="12" r="2"/>
            <circle cx="9" cy="18" r="2"/><circle cx="15" cy="18" r="2"/>
          </svg>
        </span>
        <div class="task-card__body">
          <InlineEdit
            :text="task.title"
            @change="(val: string) => change_task_title(task.id, val)"
          />
          <p v-if="task.description">{{ task.description }}</p>
        </div>
        <button
          class="btn-danger btn-icon task-card__delete"
          @click="delete_task(list_id, task.id)"
          title="Delete task"
        >
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </button>
      </div>

      <div v-if="Object.keys(tasks).length === 0" class="empty-state" style="padding: 1.5rem 1rem;">
        <p class="empty-state__text">No tasks yet</p>
      </div>
    </div>

    <!-- Footer — add task -->
    <div class="column__footer">
      <button
        v-if="!showAddTask"
        class="add-task-trigger"
        @click="showAddTask = true"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="12" y1="5" x2="12" y2="19"/>
          <line x1="5" y1="12" x2="19" y2="12"/>
        </svg>
        Add task
      </button>

      <form
        v-else
        class="add-task-form"
        @submit="handleCreateTask"
      >
        <input type="text" name="name" placeholder="Task name..." autofocus />
        <div class="add-task-form__actions">
          <button type="submit" class="btn-primary">Add</button>
          <button type="button" class="btn-ghost" @click="showAddTask = false">Cancel</button>
        </div>
      </form>
    </div>
  </div>
</template>import type { WS_BASE_URL } from '../settings'
import type { WS_BASE_URL } from '../settings'
